### ISSUE TITLE
[assets] 테마 작성, 문장 작성 시 필요한 에셋들

### ISSUE THREAD

**Issue by qodhrkawk** [Sopt-Mongle/MongleiOS#13]
에셋 제플린에 더 추가되는 거 아니면 이것만 추가하면 테마,문장 작성 뷰에서는 더 필요 없을듯~

테마 작성
- [x] warning (등록하기 눌렀을 때 작성 안눌렀을 시 나오는 작은 경고 에셋

- [x] mgm2 (테마 등록했을 때 나오는 몽글 캐릭터)

- [x] X button-> 이거는 지금 > 랑 < 로 나눠져서 올라와 있길래 디자인한테 말했음!

**Comment by Juhyeoklee** [comment]
확인~~ 얼른 올려줄꼐요 ~~

**Comment by Juhyeoklee** [comment]
x 버튼 빼고 올림
