### ISSUE TITLE
[asset] 테마정보 화면 에셋 테마

### ISSUE THREAD

**Issue by Juhyeoklee** [Sopt-Mongle/MongleiOS#26]
- [x] 테마정보 큐레이터 이미지
- [x] 테마 정보 하트 이미지
- [x] 테마 정보 북마크 아이콘
- [x] 테마 북마크 버튼 이미지

**Comment by qodhrkawk** [comment]
- [x] 128 - 문장쓰기(테마에 문장쓰기) asset 추가

- [x]  x버튼(writingTheme3BtnClose) 테마 만들기에 있음

- [x] themeWritingSentenceBook4ImgBook - 책 검색 테이블 셀 그림

- [x] mainImgTheme2 - 테마 선택 뷰에서 사진
