### ISSUE TITLE
[asset] 에셋 추가 요청

### ISSUE THREAD

**Issue by qodhrkawk** [Sopt-Mongle/MongleiOS#34]
- [x] 문장 만들기 뷰의 테마 선택에 들어가는 필터(blur)

- [x] 문장 만들기 뷰의 테마 선택 시 나타나는 체크표시 이미지

- [x] 테마 없는 문장 바탕

**Comment by qodhrkawk** [comment]
- [ ] 문장 쓰기에서 테마 선택을 할 때 나오는 체크박스

**Comment by Juhyeoklee** [comment]
- [ ] 문장 상세에서 따음표 에셋
- [ ] 문장 상세에서 테마 없을 때 뒤로가기 버튼 에셋
- [ ] 테마 보러 가기 옆에 화살표 에셋

**Comment by qodhrkawk** [comment]
- [ ] 팝업 큰 덩어리 에셋

**Comment by qodhrkawk** [comment]
- [ ] 로그인 뷰 "

- [ ] 로그인 뷰 네마리

- [ ] 로그인 뷰 |

- [ ] 로그인 뷰 배경

- [ ] 로그인 뷰 "몽글에서 책 속의 문장을 ... " 에셋
